@baseUrl = http://localhost:3000

@userNameForTesting = Luiz
@userEmailForTesting = luiz@email.com
@userPasswordForTesting = 123456
@userNewPasswordForTesting = 123456

# USER ########################################################################

### Create user
# @name createUser
POST  {{baseUrl}}/user/
Content-Type: application/json

{
    "name": "{{userNameForTesting}}",
    "email": "{{userEmailForTesting}}",
    "password": "{{userPasswordForTesting}}"
}

### Get user
# @name createUser
GET  {{baseUrl}}/user/c82cf8e9-4162-4353-a016-1b47e317dde4
Content-Type: application/json

### Get all user
# @name createUser
GET  {{baseUrl}}/user
