@baseUrl = http://localhost:3000

@userNameForTesting = Luiz
@userEmailForTesting = luiz@email.com
@userPasswordForTesting = 123456
@userNewPasswordForTesting = 123456

### Auth login
# @name authLogin
POST  {{baseUrl}}/auth/user/
Content-Type: application/json

{
    "email": "{{userEmailForTesting}}",
    "password": "{{userPasswordForTesting}}"
}

